# Generated by Django 5.0.1 on 2024-02-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paldex', '0002_alter_palmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palmodel',
            name='image',
            field=models.URLField(verbose_name='Image'),
        ),
    ]
