# Generated by Django 5.0.1 on 2024-02-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paldex', '0006_alter_palmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palmodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
