# Generated by Django 5.0.1 on 2024-02-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pal',
        ),
    ]
