# Generated by Django 3.1.14 on 2024-02-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_fireteam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireteam',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
