# Generated by Django 3.1.14 on 2024-02-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paldex', '0010_auto_20240221_0731'),
        ('members', '0010_auto_20240221_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fireteam',
            name='members',
        ),
        migrations.AddField(
            model_name='fireteam',
            name='members',
            field=models.ManyToManyField(related_name='fire_teams_joined', to='paldex.PalModel'),
        ),
    ]
