# Generated by Django 5.0.2 on 2024-02-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20240221_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireteam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
