# Generated by Django 4.2.9 on 2024-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paldex', '0011_alter_palmodel_id_alter_todoitem_id'),
        ('members', '0011_alter_fireteam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fireteam',
            name='members',
        ),
        migrations.AddField(
            model_name='fireteam',
            name='members',
            field=models.ManyToManyField(default=list, related_name='fire_teams_joined', to='paldex.palmodel'),
        ),
    ]
